# Generated by Django 2.2.4 on 2019-08-02 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balay', '0002_auto_20190802_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 12, 36, 25, 737528, tzinfo=utc)),
        ),
    ]
