# Generated by Django 2.2.4 on 2019-08-03 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balay', '0004_auto_20190803_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 13, 3, 51, 893235, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
