# Generated by Django 2.2.4 on 2019-08-03 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balay', '0005_auto_20190803_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 16, 39, 1, 102545, tzinfo=utc)),
        ),
    ]
