# Generated by Django 2.2.4 on 2019-08-03 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balay', '0006_auto_20190803_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 16, 55, 20, 133408, tzinfo=utc)),
        ),
    ]
