# Generated by Django 2.2.4 on 2019-08-03 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balay', '0007_auto_20190803_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 8, 3, 17, 12, 46, 256601, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Работы',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 17, 12, 46, 255602, tzinfo=utc)),
        ),
    ]
