# Generated by Django 2.2.4 on 2019-08-03 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balay', '0008_auto_20190803_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 17, 16, 24, 201819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='works',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 17, 16, 24, 203818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='works',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='work/'),
        ),
    ]
